//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public string device { get; set; }
        public string Stedsnavn { get; set; }
        public string Beskrivelse { get; set; }
        public decimal Breddegrad { get; set; }
        public decimal Lengdegrad { get; set; }
        public bool Aktiv { get; set; }
        public string uuid { get; set; }
    }
}
